[general]
live_config_reload = true

[font]
normal = { family = "0xProto Nerd Font" }
size = 13
builtin_box_drawing = true
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }

# [window]
# padding = { x = 20, y = 25 }

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[env]
WINIT_X11_SCALE_FACTOR = "1"
